### ISSUE TITLE
heat map of Keys appreciated.

### ISSUE THREAD

**Issue by vitaminncpp** [SKR301/hot-key-board#3]
- Currently your application only shows typed keys in plain fashion.
- Heat Map will be more suitable in case user wants to analyse frequency of its key presed,
- Thank you

**Comment by SKR301** [comment]
Yeah, that's the whole point of the project!
It actually shows the heat map.
Maybe you haven't used it enough.

**Comment by vitaminncpp** [comment]
- Good.
- I got it.
- But my suggestion is you should adjust contrast dynamically e.g based on current total keys pressed.
- Thank you.
